version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/focyl"
    restart: always
    ports:
      - 4408:3306
    environment:
      MYSQL_ROOT_PASSWORD: marcos
      MYSQL_DATABASE: focyl
      MYSQL_USER: user
      MYSQL_PASSWORD: marcos
# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9898:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: marcos 

